/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#60000e',
        'inverse-surface': '#faf8ff',
        'error-dim': '#bb5551',
        'tertiary-dim': '#fb7373',
        'on-tertiary-container': '#490008',
        'secondary': '#8f9fb7',
        'primary-fixed-dim': '#50ebd5',
        'on-secondary-container': '#b0c0da',
        'on-error': '#490106',
        'tertiary-fixed-dim': '#ea6767',
        'on-tertiary-fixed-variant': '#5b000d',
        'secondary-fixed': '#d3e4fe',
        'surface-bright': '#1a2a54',
        'surface-dim': '#0a0e1a',
        'on-primary-fixed': '#004840',
        'surface-container-high': '#141e3b',
        'outline': '#68749c',
        'inverse-on-surface': '#515463',
        'on-primary': '#004941',
        'surface-container-highest': '#172447',
        'background': '#0a0e1a',
        'surface-container-low': '#0d1324',
        'on-primary-fixed-variant': '#00675c',
        'tertiary-container': '#fb7373',
        'surface': '#0a0e1a',
        'on-primary-container': '#4ae7d1',
        'primary-fixed': '#62fae3',
        'inverse-primary': '#006b60',
        'error-container': '#7f2927',
        'on-secondary': '#102134',
        'on-surface-variant': '#9daad4',
        'on-background': '#dfe4ff',
        'secondary-container': '#2d3c51',
        'secondary-fixed-dim': '#c5d6f0',
        'on-error-container': '#ff9993',
        'outline-variant': '#3a476c',
        'surface-container': '#11192f',
        'surface-container-lowest': '#000000',
        'tertiary-fixed': '#fb7373',
        'secondary-dim': '#8f9fb7',
        'primary-dim': '#22cfba',
        'error': '#ee7d77',
        'on-surface': '#dfe4ff',
        'surface-variant': '#172447',
        'tertiary': '#ff8887',
        'surface-tint': '#3cddc7',
        'primary': '#3cddc7',
        'on-tertiary-fixed': '#000000',
        'on-secondary-fixed-variant': '#4d5d73',
        'primary-container': '#005047',
        'on-secondary-fixed': '#314055',
        'status-healthy': '#4ADE80',
        'status-warning': '#FBBF24',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
